/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GxButton: typeof import('./src/components/guoxin/GxButton.vue')['default']
    GxCard: typeof import('./src/components/guoxin/GxCard.vue')['default']
    GxChip: typeof import('./src/components/guoxin/GxChip.vue')['default']
    GxFontScaleNav: typeof import('./src/components/guoxin/GxFontScaleNav.vue')['default']
    GxLoginModal: typeof import('./src/components/guoxin/GxLoginModal.vue')['default']
    GxNavBar: typeof import('./src/components/guoxin/GxNavBar.vue')['default']
    GxRegionPicker: typeof import('./src/components/guoxin/GxRegionPicker.vue')['default']
    GxSourceBackBar: typeof import('./src/components/guoxin/GxSourceBackBar.vue')['default']
    ProfileReadingRecordList: typeof import('./src/components/guoxin/ProfileReadingRecordList.vue')['default']
    ReportChapter: typeof import('./src/components/guoxin/report/ReportChapter.vue')['default']
    ReportComponentRenderer: typeof import('./src/components/guoxin/report/ReportComponentRenderer.vue')['default']
    ReportFooter: typeof import('./src/components/guoxin/report/ReportFooter.vue')['default']
    ReportHero: typeof import('./src/components/guoxin/report/ReportHero.vue')['default']
    ReportPieDonut: typeof import('./src/components/guoxin/report/ReportPieDonut.vue')['default']
    ReportPillarCard: typeof import('./src/components/guoxin/report/ReportPillarCard.vue')['default']
    ReportRichText: typeof import('./src/components/guoxin/report/ReportRichText.vue')['default']
    ReportSectionBlock: typeof import('./src/components/guoxin/report/ReportSectionBlock.vue')['default']
    ReportView: typeof import('./src/components/guoxin/report/ReportView.vue')['default']
    UConfigProvider: typeof import('uview-pro/components/u-config-provider/u-config-provider.vue')['default']
    UIcon: typeof import('uview-pro/components/u-icon/u-icon.vue')['default']
    ULink: typeof import('uview-pro/components/u-link/u-link.vue')['default']
    UNavbar: typeof import('uview-pro/components/u-navbar/u-navbar.vue')['default']
    UText: typeof import('uview-pro/components/u-text/u-text.vue')['default']
  }
}
