/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GxAvatarSwitcher: typeof import('./src/components/guoxin/chat/GxAvatarSwitcher.vue')['default']
    GxBaziProfileModal: typeof import('./src/components/guoxin/chat/GxBaziProfileModal.vue')['default']
    GxButton: typeof import('./src/components/guoxin/GxButton.vue')['default']
    GxCard: typeof import('./src/components/guoxin/GxCard.vue')['default']
    GxChatComposer: typeof import('./src/components/guoxin/chat/GxChatComposer.vue')['default']
    GxChatFeedbackModal: typeof import('./src/components/guoxin/chat/GxChatFeedbackModal.vue')['default']
    GxChatFollowupPanel: typeof import('./src/components/guoxin/chat/GxChatFollowupPanel.vue')['default']
    GxChatHeader: typeof import('./src/components/guoxin/chat/GxChatHeader.vue')['default']
    GxChatLimitModal: typeof import('./src/components/guoxin/chat/GxChatLimitModal.vue')['default']
    GxChatLoginModal: typeof import('./src/components/guoxin/chat/GxChatLoginModal.vue')['default']
    GxChatMessageList: typeof import('./src/components/guoxin/chat/GxChatMessageList.vue')['default']
    GxChatQuotaCard: typeof import('./src/components/guoxin/chat/GxChatQuotaCard.vue')['default']
    GxChatReportAd: typeof import('./src/components/guoxin/chat/GxChatReportAd.vue')['default']
    GxChatThread: typeof import('./src/components/guoxin/chat/GxChatThread.vue')['default']
    GxChip: typeof import('./src/components/guoxin/GxChip.vue')['default']
    GxCreditsIcon: typeof import('./src/components/guoxin/GxCreditsIcon.vue')['default']
    GxCustomerServiceModal: typeof import('./src/components/guoxin/GxCustomerServiceModal.vue')['default']
    GxFontScaleNav: typeof import('./src/components/guoxin/GxFontScaleNav.vue')['default']
    GxInviteModal: typeof import('./src/components/guoxin/chat/GxInviteModal.vue')['default']
    GxLoginModal: typeof import('./src/components/guoxin/GxLoginModal.vue')['default']
    GxNavBar: typeof import('./src/components/guoxin/GxNavBar.vue')['default']
    GxQuestionBoard: typeof import('./src/components/guoxin/chat/GxQuestionBoard.vue')['default']
    GxRegionPicker: typeof import('./src/components/guoxin/GxRegionPicker.vue')['default']
    GxSourceBackBar: typeof import('./src/components/guoxin/GxSourceBackBar.vue')['default']
    GxUserBrief: typeof import('./src/components/guoxin/GxUserBrief.vue')['default']
    ProfileReadingRecordList: typeof import('./src/components/guoxin/ProfileReadingRecordList.vue')['default']
    ReportChapter: typeof import('./src/components/guoxin/report/ReportChapter.vue')['default']
    ReportComponentRenderer: typeof import('./src/components/guoxin/report/ReportComponentRenderer.vue')['default']
    ReportFooter: typeof import('./src/components/guoxin/report/ReportFooter.vue')['default']
    ReportHero: typeof import('./src/components/guoxin/report/ReportHero.vue')['default']
    ReportPieDonut: typeof import('./src/components/guoxin/report/ReportPieDonut.vue')['default']
    ReportPillarCard: typeof import('./src/components/guoxin/report/ReportPillarCard.vue')['default']
    ReportRichText: typeof import('./src/components/guoxin/report/ReportRichText.vue')['default']
    ReportSectionBlock: typeof import('./src/components/guoxin/report/ReportSectionBlock.vue')['default']
    ReportView: typeof import('./src/components/guoxin/report/ReportView.vue')['default']
    UConfigProvider: typeof import('uview-pro/components/u-config-provider/u-config-provider.vue')['default']
    UIcon: typeof import('uview-pro/components/u-icon/u-icon.vue')['default']
    ULink: typeof import('uview-pro/components/u-link/u-link.vue')['default']
    UNavbar: typeof import('uview-pro/components/u-navbar/u-navbar.vue')['default']
    UText: typeof import('uview-pro/components/u-text/u-text.vue')['default']
  }
}
