/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AiDeductionEchart: typeof import('./src/components/ai_deduction_echart/aiDeductionEchart.vue')['default']
    AiDeductionLoading: typeof import('./src/components/ai_deduction_loading/aiDeductionLoading.vue')['default']
    AiDescription: typeof import('./src/components/ai_deduction_echart/aiDescription.vue')['default']
    AiTable: typeof import('./src/components/ai_deduction_echart/aiTable.vue')['default']
    AnalysisModel: typeof import('./src/components/bazi_son_page/analysisModel.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLinks: typeof import('./src/components/AppLinks.vue')['default']
    AppLogos: typeof import('./src/components/AppLogos.vue')['default']
    AppThemes: typeof import('./src/components/AppThemes.vue')['default']
    DecipherModel: typeof import('./src/components/bazi_son_page/decipherModel.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    LoginDialog: typeof import('./src/components/login_dialog/loginDialog.vue')['default']
    LunarDatetimePicker: typeof import('./src/components/lunar_datetime_picker/LunarDatetimePicker.vue')['default']
    SketTTimer: typeof import('./src/components/sket_t_timer/SketTTimer.vue')['default']
    TestHttp: typeof import('./src/components/TestHttp.vue')['default']
    TraditionModel: typeof import('./src/components/bazi_son_page/traditionModel.vue')['default']
    UBadge: typeof import('uview-pro/components/u-badge/u-badge.vue')['default']
    UButton: typeof import('uview-pro/components/u-button/u-button.vue')['default']
    UCol: typeof import('uview-pro/components/u-col/u-col.vue')['default']
    UCollapse: typeof import('uview-pro/components/u-collapse/u-collapse.vue')['default']
    UCollapseItem: typeof import('uview-pro/components/u-collapse-item/u-collapse-item.vue')['default']
    UConfigProvider: typeof import('uview-pro/components/u-config-provider/u-config-provider.vue')['default']
    UDivider: typeof import('uview-pro/components/u-divider/u-divider.vue')['default']
    UEmpty: typeof import('uview-pro/components/u-empty/u-empty.vue')['default']
    UForm: typeof import('uview-pro/components/u-form/u-form.vue')['default']
    UFormItem: typeof import('uview-pro/components/u-form-item/u-form-item.vue')['default']
    UIcon: typeof import('uview-pro/components/u-icon/u-icon.vue')['default']
    UInput: typeof import('uview-pro/components/u-input/u-input.vue')['default']
    ULineProgress: typeof import('uview-pro/components/u-line-progress/u-line-progress.vue')['default']
    ULink: typeof import('uview-pro/components/u-link/u-link.vue')['default']
    ULoading: typeof import('uview-pro/components/u-loading/u-loading.vue')['default']
    UMask: typeof import('uview-pro/components/u-mask/u-mask.vue')['default']
    UModal: typeof import('uview-pro/components/u-modal/u-modal.vue')['default']
    UNavbar: typeof import('uview-pro/components/u-navbar/u-navbar.vue')['default']
    UPagination: typeof import('uview-pro/components/u-pagination/u-pagination.vue')['default']
    UPicker: typeof import('uview-pro/components/u-picker/u-picker.vue')['default']
    UPopup: typeof import('uview-pro/components/u-popup/u-popup.vue')['default']
    URow: typeof import('uview-pro/components/u-row/u-row.vue')['default']
    USubsection: typeof import('uview-pro/components/u-subsection/u-subsection.vue')['default']
    UTabs: typeof import('uview-pro/components/u-tabs/u-tabs.vue')['default']
    UTag: typeof import('uview-pro/components/u-tag/u-tag.vue')['default']
    UText: typeof import('uview-pro/components/u-text/u-text.vue')['default']
    UToast: typeof import('uview-pro/components/u-toast/u-toast.vue')['default']
    UTopTips: typeof import('uview-pro/components/u-top-tips/u-top-tips.vue')['default']
    UVerificationCode: typeof import('uview-pro/components/u-verification-code/u-verification-code.vue')['default']
    XingMingNameBox: typeof import('./src/components/xing_ming/XingMingNameBox.vue')['default']
  }
}
