/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index" |
  "/pages/credits/index" |
  "/pages/credits/member" |
  "/pages/credits/paid" |
  "/pages/invite/accept" |
  "/pages/jiedu/chat" |
  "/pages/jiedu/complete" |
  "/pages/jiedu/detail" |
  "/pages/jiedu/processing" |
  "/pages/jiedu/report-confirm" |
  "/pages/jiedu/setup" |
  "/pages/legal/privacy" |
  "/pages/legal/service" |
  "/pages/mine/index" |
  "/pages/profile/create" |
  "/pages/profile/list" |
  "/pages/users/index";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
