/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index" |
  "/pages/http/http" |
  "/pages/login/login" |
  "/pages/meiHua/meiHua" |
  "/pages/shengPing/shengPing" |
  "/pages/xingMing/xingMing" |
  "/pages/xingMing/xingMingDetail" |
  "/pages/xingMing/xingMingLiuGeDetail" |
  "/pages/yangPan/yangPan" |
  "/pages/meiHua/about/about" |
  "/pages/meiHua/baoshu/baoshu" |
  "/pages/meiHua/details/details" |
  "/pages/meiHua/shijian/shijian" |
  "/pages/meiHua/zhiding/zhiding" |
  "/pages/shengPing/aiDeductionHistory/aiDeductionHistory" |
  "/pages/shengPing/aiDeductionPage/aiDeductionHistoryPage" |
  "/pages/shengPing/aiDeductionPage/aiDeductionPage" |
  "/pages/shengPing/shengPingDetails/shengPingDetails" |
  "/pages/yangPan/yangPanDetails/yangPanDetails" |
  "/pages/meiHua/about/explain/explain";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
